### ISSUE TITLE
could not create generator for map [CarmlSubjectMap [getGraphMaps()=[], getClasses()=[http://www.fitnessontology.com/#HeartRate], getReference()=null, getInverseExpression()=null, getTemplate()=null, getTermType()=BLANK_NODE, getConstant()=null, getFunctionValue()=null]]

### ISSUE THREAD

**Issue by chiarisilver** [carml/carml#34]
Hi, 
I am trying to use the CARML library in order to map two JSON files through my RML mapping file.
When I run my code, I get this error: 
`
Exception in thread "main" java.lang.RuntimeException: could not create generator for map [CarmlSubjectMap [getGraphMaps()=[], getClasses()=[http://www.fitnessontology.com/#HeartRate], getReference()=null, getInverseExpression()=null, getTemplate()=null, getTermType()=BLANK_NODE, getConstant()=null, getFunctionValue()=null]]
	at com.taxonic.carml.engine.TermGeneratorCreator.getGenerator(TermGeneratorCreator.java:134)
	at com.taxonic.carml.engine.TermGeneratorCreator.getSubjectGenerator(TermGeneratorCreator.java:99)
	at com.taxonic.carml.engine.RmlMapper.createSubjectMapper(RmlMapper.java:502)
	at com.taxonic.carml.engine.RmlMapper.createTriplesMapper(RmlMapper.java:534)
	at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:371)
	at com.taxonic.carml.engine.RmlMapper.lambda$map$2(RmlMapper.java:316)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:316)
	at buildJENARML.RMLMAPPER.main(RMLMAPPER.java:59) `

This is my Java code: 

`
	static final String directoryRMLMapper = "C:\\Users\\Chiara\\Desktop\\FITIBIT\\fitbit.rml.ttl";
	static final String directoryFile = "C:\\Users\\Chiara\\Desktop\\FITIBIT\\fitbitHeartRate.json";
	static final String directoryFileD = "C:\\Users\\Chiara\\Desktop\\FITIBIT\\fitbitWeight.json";
	
	public static void main(String args[]) throws IOException{

		InputStream in = FileManager.get().open(directoryFile);
		if (in == null) {
			throw new IllegalArgumentException("File not found");
		}
		
		InputStream ind = FileManager.get().open(directoryFileD);
		if (ind == null) {
			throw new IllegalArgumentException("File not found");
		}
	
		RmlMapper mapper = RmlMapper.newBuilder().build();
		
		mapper.bindInputStream("stream-A",in);
		mapper.bindInputStream("stream-B", ind);

		 Set<TriplesMap> mapping =
			RmlMappingLoader
				.build()
				.load(Paths.get(directoryRMLMapper), RDFFormat.TURTLE);

		Model result = mapper.map(mapping);
		
		result.forEach(System.out::println);
	
	}
}
`

Follows part of my code fitbit.rml.ttl for the LogicalSource. 
First JSON file: 

rml:logicalSource [
	rml:source [a carml:Stream ;
			carml:streamName "stream-A" ;];
	rml:referenceFormulation ql:JSONPath;
	rml:iterator "$.activities-heart";
];

And for the second JSON file:

rml:logicalSource [
	rml:source [a carml:Stream ;
			carml:streamName "stream-B" ;];
	rml:referenceFormulation ql:JSONPath;
	rml:iterator "$.weight";
];

Thanks for any help,
Chiara

**Comment by chiarisilver** [comment]
Unfortunately I can not post all the code. This is an example of a subject map. The error could come from the blankNode?

rr:subjectMap [
	rr:termType rr:BlankNode; 
	rr:class fo:TimeInterval;
];


Thanks,
Chiara

**Comment by pmaria** [comment]
Hey @chiarisilver,

Yes that is the problem indeed. In the implementation of CARML we followed the R2RML spec rules for term maps. Those require you to provide an id value for a blank node. You can do this by adding an `rml:reference`, or `rr:template` to create a unique, or not so unique blank node identifier.

Regards,
Pano

**Comment by pmaria** [comment]
@chiarisilver Did you manage to solve this? 
If yes, could you please close this issue. 
If no, can we help you further?

**Comment by chiarisilver** [comment]
Yes thank you!
