### ISSUE TITLE
JoinCondition : null pointer exception

### ISSUE THREAD

**Issue by miyamotodan** [carml/carml#40]
Hi!

I'm trying to use the CLI ( https://github.com/pmaria/carml-jar ), it works fine! but I get an exception when I try to use a JoinCondition like this:

`rr:predicateObjectMap [
    rr:predicate clvapit:hasRegion ;
    rr:objectMap [
      rr:parentTriplesMap <#csv_source_istat>;
      rr:joinCondition [
        rr:child "CODISTAT";
        rr:parent "CODICE_COMUNE_FORMATO_ALFANUMERICO";
      ] ;
    ] ;
  ] ;`

the exception is

`java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at com.skemu.rdf.carml.CarmlJar.main(CarmlJar.java:10) [classes!/:0.0.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [carml-jar-0.0.2.jar:0.0.2]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [carml-jar-0.0.2.jar:0.0.2]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [carml-jar-0.0.2.jar:0.0.2]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [carml-jar-0.0.2.jar:0.0.2]
Caused by: java.lang.NullPointerException: null
        at com.taxonic.carml.engine.RmlMapper.getTriplesMapperComponents(RmlMapper.java:515) ~[carml-engine-0.1.2.jar!/:na]
        at com.taxonic.carml.engine.RmlMapper.createParentTriplesMapper(RmlMapper.java:540) ~[carml-engine-0.1.2.jar!/:na]
        at com.taxonic.carml.engine.RmlMapper.createRefObjectMapper(RmlMapper.java:552) ~[carml-engine-0.1.2.jar!/:na]
`

the files are attached.

Thanks in advance

[example.zip](https://github.com/carml/carml/files/1899379/example.zip)

**Comment by pmaria** [comment]
Hi @miyamotodan,

When you specify the parent triples map (`rr:parentTriplesMap`) you are pointing to the logical source (`<#csv_source_istat>`) instead of a triples map. Presumably you should point to the `<#Regione>` triples map

**Comment by miyamotodan** [comment]
Yes!! You are right! Thanks
