### ISSUE TITLE
Cannot use carml:source/rml:source

### ISSUE THREAD

**Issue by nicky508** [carml/carml#65]
Hi,

I have a question about the use of hardcoded inputfiles in the mapping. Until now, I used streams. But I face the problem of vast input files, which will cause Java memory issues errors. Somewhere I read that the Saxion lib does not read the complete xml file into memory (ofcourse streams do). Therefore I am trying to point the mapping to the xml file and hopefully elude the memory issue. However, I do not succeed pointing to the input file from the mapping file without errors.

When I'm using carml:url :

```
<#SubjectMapping> a rr:TriplesMap ;
   rml:logicalSource [
     rml:source [
       #a carml:Stream ;
 	  carml:url "c:\tools\inutFile.xml" ;
 	   carml:declaresNamespace [
        carml:namespacePrefix "ns2" ;
         carml:namespaceName "ch.voev.nova.pflege.common.exporter.datenrelease" ;
       ] ;
     ] ;
     rml:referenceFormulation ql:XPath ;
     rml:iterator "/subsystemFQF/partners/partner" ;
  ] ;
```

I get the following exception:
```
Exception in thread "main" java.lang.RuntimeException: could not resolve source [com.taxonic.carml.model.impl.CarmlFileSource@29626d54[
  url=c:\tools\inutFile.xml,
  id=node1cpef4db5x2,
  label=<null>
]]
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.lambda$apply$1(RmlMapper.java:282)
        at java.util.Optional.orElseThrow(Unknown Source)
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.apply(RmlMapper.java:281)
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.apply(RmlMapper.java:265)
        at com.taxonic.carml.logical_source_resolver.LogicalSourceResolver.lambda$bindSource$0(LogicalSourceResolver.java:16)
        at com.taxonic.carml.engine.TriplesMapper.map(TriplesMapper.java:44)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:370)
        at com.taxonic.carml.engine.RmlMapper.lambda$map$2(RmlMapper.java:312)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:312)
        at info.resc.rml.carml.cli.Main.convertFile(Main.java:136)
        at info.resc.rml.carml.cli.Main.main(Main.java:71)
```

When I use the regular rml:source:
```
<#SubjectMapping> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source "c:\tools\inutFile.xml" ;
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/subsystemFQF/partners/partner" ;
  ] ;
```
I get the following issue:
```
Exception in thread "main" java.lang.RuntimeException: could not resolve source [c:\Users\Nicky\Documents\NETAGE\Zazuko\Nova\nova-xml\nova.xml]
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.lambda$apply$1(RmlMapper.java:282)
        at java.util.Optional.orElseThrow(Unknown Source)
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.apply(RmlMapper.java:281)
        at com.taxonic.carml.engine.RmlMapper$CompositeSourceResolver.apply(RmlMapper.java:265)
        at com.taxonic.carml.logical_source_resolver.LogicalSourceResolver.lambda$bindSource$0(LogicalSourceResolver.java:16)
        at com.taxonic.carml.engine.TriplesMapper.map(TriplesMapper.java:44)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:370)
        at com.taxonic.carml.engine.RmlMapper.lambda$map$2(RmlMapper.java:312)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:312)
        at info.resc.rml.carml.cli.Main.convertFile(Main.java:136)
        at info.resc.rml.carml.cli.Main.main(Main.java:71)
```

At this moment I'm a bit lost in how to fix this issue, the carml:url seems to be prefered, but seems not to work. The java code responsible for the execution is:
```
private static Model convertFile(InputStream inputStream, boolean useStream){
		Set<TriplesMap> mapping =
				RmlMappingLoader
				.build()
				.load(Paths.get(Main.mappingFile), RDFFormat.TURTLE);
		RmlMapper mapper = RmlMapper.newBuilder()
				.setLogicalSourceResolver(Rdf.Ql.XPath, new XPathResolver())
				.build();
		if(useStream){
			mapper.bindInputStream(inputStream);
		}
		return mapper.map(mapping);
	}
```

**Comment by pmaria** [comment]
Hi @nicky508 

You have to add a `.fileResolver(Paths.get("YOUR_BASE_PATH_HERE"))` when building your RmlMapper. I agree that this isn't very clear currently. I'll see what we can do about that in the docs.

However, I'm afraid that won't solve your problem. We're currently not using memory mapped files (or something like that) internally to handle large files, so CARML currently reads provided source in memory. There is still some work to do to support this.

For large sources that are splittable, it's best to arrange this outside of CARML.
